name: ❖ Validate

on:
  workflow_call:
    inputs:
      stage:
        description: 'the environment to validate'
        required: true
        type: string
        default: 'staging'
      stage-url:
        description: 'the URL of the environment'
        required: true
        type: string
        default: https://${{ vars.SUBDOMAIN_NAME }}.walletconnect.com/health

jobs:
  health-check:
    name: Health Check - ${{ inputs.stage }}
    runs-on:
      labels: ubuntu-latest
    environment:
      name: ${{ inputs.stage }}
      url: ${{ inputs.stage-url }}
    steps:
      - name: health-check
        run: curl "${{ inputs.stage-url }}"

  integration-tests:
    name: Integration Tests - ${{ inputs.stage }}
    runs-on:
      labels: ubuntu-latest
    environment:
      name: ${{ inputs.stage }}
      url: ${{ inputs.stage-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_SUBMODULE_ACCESS_TOKEN || github.token }}

      - name: "Install Rust ${{ inputs.version }}"
        uses: WalletConnect/actions-rs/toolchain@2.0.0
        with:
          toolchain: ${{ vars.RUST_VERSION }}
          profile: 'default'
          override: true

      - name: "Run Integration Tests"
        uses: WalletConnect/actions-rs/cargo@2.0.0
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          RPC_URL: ${{ inputs.stage-url }}
        with:
          command: test
          args: --test integration
