name: Deploy App

on:
  workflow_call:
    inputs:
      version:
        description: 'The ECR tag to deploy'
        type: string
        required: true
      image-name:
        description: 'The name of the image to deploy'
        type: string
        default: ${{ vars.IMAGE_NAME }}
      stage:
        description: 'The environment to deploy to'
        type: string
        required: true
      stage-url:
        description: 'The URL of the environment'
        type: string
        required: true
      aws-region:
        description: 'The AWS region to deploy to'
        type: string
        default: ${{ vars.AWS_REGION }}
      aws-role-arn:
        description: 'The ARN of the AWS role to assume for the deployment'
        type: string
        required: true
      run-group:
        description: 'The run group to use for the actions'
        type: string
        default: ${{ vars.RUN_GROUP }}

concurrency: deploy-${{ inputs.stage }}

permissions:
  contents: read
  id-token: write

jobs:
  deploy-app:
    name: Deploy App `${{ inputs.stage }}`
    runs-on:
      group: ${{ inputs.run-group }}
    environment:
      name: ${{ inputs.stage }}
      url: ${{ inputs.environment_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-role-arn }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to ECR repository
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Deploy image to ECS
        id: deploy
        uses: WalletConnect/actions/aws/ecs/deploy-image/@2.2.1
        with:
          aws-role-arn: ${{ inputs.aws-role-arn }}
          aws-region: ${{ inputs.aws-region }}
          cluster-name: wc-${{ inputs.aws-region }}-${{ inputs.stage }}-${{ inputs.image-name }}-cluster
          service-name: wc-${{ inputs.aws-region }}-${{ inputs.stage }}-${{ inputs.image-name }}-service
          task-definition-name: wc-${{ inputs.aws-region }}-${{ inputs.stage }}-${{ inputs.image-name }}
          image-name: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image-name }}:${{ inputs.version }}
