name: Release - Get Deployed Version

on:
  workflow_call:
    inputs:
      task-name:
        description: 'The name of the ECS task'
        type: string
        default: ${{ vars.IMAGE_NAME }}
      aws-region:
        description: 'The AWS region where the task is defined'
        type: string
        default: ${{ vars.AWS_REGION }}
      aws-role-arn:
        description: 'The ARN of the AWS role to assume to retrieve the ECS task information'
        type: string
        required: true
      run-group:
        description: 'The run group to use for the actions'
        type: string
        default: ${{ vars.RUN_GROUP }}
    outputs:
      version:
        description: 'The image version of the current ECS task definition'
        value: ${{ jobs.get_version.outputs.version }}

jobs:
  get_version:
    name: Lookup ECS
    runs-on:
      group: ${{ inputs.run-group }}
    steps:
      - name: Get task definition from ECS
        id: get_task
        uses: WalletConnect/actions/aws/ecs/get-task-image/@2.2.0
        with:
          aws-role-arn: ${{ inputs.aws-role-arn }}
          aws-region: ${{ inputs.aws-region }}
          task-definition-name: ${{ inputs.task-name }}
          container-name: ${{ inputs.task-name }}
    outputs:
      version: ${{ steps.get_task.outputs.tag }}

  display_version:
    name: Version ➠ ${{ needs.get_version.outputs.version }}
    needs: [ get_version ]
    runs-on:
      group: ${{ inputs.run-group }}
    steps:
      - run: echo "Version = ${{ needs.get_version.outputs.version }}"
